### ISSUE TITLE
Allow scripts to be hidden

### ISSUE THREAD

**Issue by DamienCassou** [pillar-markup/pillar#101]
While writing pillar documents for teaching, we often want a version of the document for students and a version for teachers with some details and solutions. It would be nice to write just one document and to allow some scripts to be hidden for students and visible for teachers. Something like:

```pillar
You should now implement method foo.

[[[hideable=true
TheClass>>foo
  ...
]]]
```

The user could then generate 2 output files, one with only the sentence, one with both the sentence and the method implementation. The difference could be done by passing a parameter `showHideable=true` or `false`, either in the `pillar.conf` or on the command line.

**Comment by YannDub** [comment]
I have tried to do this feature, but I don't find the way to get the pillar configuration to get the value of the parameter `showHideable`.

**Comment by jecisc** [comment]
During the export PRDocumentWriter have an access to the configuration object. (PRDocumentWriter>>#configuration).
During the #visitScript: you should be able to check it and do something as:

`visitScript: aScript
    (self configuration showHideable and: [ aScript isHideable ]) ifTrue: [ ^ self ].

    "Else still use the old behavior"
`

**Comment by DamienCassou** [comment]
Instead of doing that in all exporters, I would add a new `Transformer`

**Comment by YannDub** [comment]
I understood how work the `Transformer`, but I don't undertand how choosing the `pillarTransformer` value in 
```
<pillarTransformer: ??? key: 'scriptShowHideable' documentation:
		'I visit a document and I hide the script with the ==hideable==' parameter at ==true==>
```

**Comment by jecisc** [comment]
This value define a priority. This priority will be use to sort the transformation because some need to be executed before some others.
I don't have in mind anymore all the transformers so I cannot help you right now to find the right priority. If you have trouble with it I can take a look when I will be at home and not at the company.

**Comment by YannDub** [comment]
I can hide a script now, but I think a parameter showHideable is not suitable because I have created a new Transformer to do that.
So I think it would be better to have a transformer parameter which would be disabled to hide the script

**Comment by jecisc** [comment]
If there is a transformer, indeed you do not need a new configuration parameter :)

**Comment by YannDub** [comment]
I had this with :
- Pillar-Model-YannDubois.244
- Pillar-ExporterCore-YannDubois.261

With the tests :
- Pillar-Tests-Model-YannDubois.179

**Comment by DamienCassou** [comment]
Good job.
