### ISSUE TITLE
Auto-capitalization of titles

### ISSUE THREAD

**Issue by DamienCassou** [pillar-markup/pillar#102]
It would be nice to have an option to activate autocapitalization of titles. For example, Pillar input:

```
!!Seaside adaptor
```

with the option activated would result in:

```latex
\section{Seaside Adaptor}
```

with capital `A`.

**Comment by jecisc** [comment]
Maybe PRNumberingLevelConfiguration could be rename "PRTitleConfiguration" and could take care of that.
This would allow the user to choose if the title should be capitalize for each title level. We could have option as "raw" (default), "capitalize", "upper case", "lower case".

**Comment by ThibaultAr** [comment]
I want to do this, but in PRNumberingLevelConfiguration you haven't access to the text of the title. would it not be better to do this in PRHeader in which you have access to the text ?

**Comment by jecisc** [comment]
The configuration is not related to the content. 
Pillar should have a configuration and a model independent. It should be during the export that the Writter use the configuration to format the text during the visit of a Header node.

So the configuration should hold the type of format and the exporter should use this configuration.

The document model should contain only raw data. It allow use to export it in pillar without loosing information.

**Comment by ThibaultAr** [comment]
It means that we have to check in every exporter the type of header ?

**Comment by jecisc** [comment]
If there is something common between multiple exporters you can add a method that will do it in the abstract superclass PRDocumentWriter.
But be careful, the Pillar exporter should not capitalize and in some exporters you can get a formatted (bold for example) text.

**Comment by ThibaultAr** [comment]
Yes but if i check if the node is a header i won't have that problem, right ?

**Comment by ThibaultAr** [comment]
And in every case we have to change all tests

**Comment by jecisc** [comment]
> And in every case we have to change all tests 

No. The default value of the configuration should be "raw", so no test should be affected.
You will need to add tests with other values in the configuration.

If an existing test about the export is broken there is a problem with your solution.

**Comment by jecisc** [comment]
> Yes but if i check if the node is a header i won't have that problem, right ?

In #visitHeader the node WILL be a header, no need for a test. But a header node can contain a Text node but also a formatted text node. So for the capitalize you need to format the first text node inside the header node. And this node can be wrap into a formatted node.

**Comment by ThibaultAr** [comment]
Ok i see so the capitalization shouldn't be the default value !
thx

**Comment by jecisc** [comment]
In my opinion it should not. 
Maybe @DamienCassou and @cdlm will disagree. What do you think?

**Comment by cdlm** [comment]
Capitalizing is an aesthetic decision and it's dependent on which typographic conventions you're following; for instance there is no such thing as capitalizing titles in french books, and even in english it depends which set of conventions you're following. See [wikipedia](https://en.wikipedia.org/wiki/Capitalization)

For many documents I'd rather have a rule checker that would report which titles are badly capitalized in the pillar sources (thus ensuring that the pillar markup is coherent and letting authors control the result on a case-by-case basis). Now maybe depending on where the text appears (chapter title vs line in table of contents vs page header/footer), it has to be capitalized or not, and in that case auto-capitalization code is needed.

NB:
- if there's an acronym in a title, it shouldn't be de-uppercased
- I'm sure there are other edge cases

**Comment by DamienCassou** [comment]
I agree with @cdlm, you should pay attention. I would write a dedicated `Transformer` for that.

**Comment by ThibaultAr** [comment]
If i understand correctly `Transformer`, it can only be active or not. So if we want to have different options for this like @jecisc said ('raw', 'capitalize', 'uppercase', 'lowercase') is it possible with a `Transformer` ?

**Comment by DamienCassou** [comment]
@ThibaultAr I think that's no problem. The transformer has access to the configuration.

**Comment by ThibaultAr** [comment]
Ok so i can create an option in the configuration which can have more values and i can just access to it in the Transformer.
Thx.

**Comment by DamienCassou** [comment]
I suggest you adapt `PRNumberingLevelConfiguration`.

**Comment by ThibaultAr** [comment]
I tried to adapt `PRNumberingLevelConfiguration` but i encounter a problem because with `Transformer` we have access to the tree with `visitDocumentGroup` so we can manipulate it but in `PRNumberingLevelConfiguration` we haven't. I don't see how we can change the content of the header, particularly if the content is not directly a Text

**Comment by jecisc** [comment]
PRNumberingLevelConfiguration is a subpart of PRPillarCinfiguration.
You can access it from the configuration via #level1, #level2, ... #level5. 
So you should be able to configure a header level and then you access to the configuration in the transformer.

**Comment by jecisc** [comment]
By the way, as I said in my first comment, if PRNumberingConfiguration hold this kind of configuration, it should be rename PRTitleConfiguration.

**Comment by ThibaultAr** [comment]
I finnaly succeed in doing this but i have a problem, this only works if the text is directly inside the header. I can't find how i can browse the pillar tree: i tried with `aGroup children flatCollect:` but inside i have to do one more to have the next floor of the tree.
The thing i want to do is go down in th tree until i find a `PRText` node and i just want to change the text of this node before visiting the rest.

For example: if i have `!""hello world"" i just want to change the text as Hello World and then visit the bold format with this text.
I hope that it was clear

**Comment by DamienCassou** [comment]
This looks like a transformer :-). In your existing transformer, in `visitHeader:`, you could set a flag indicating that the visitor is currently visiting a header. Then, you add `visitText:` and check the value of the flag. I didn't test but I think it should work.

**Comment by ThibaultAr** [comment]
It's done, a test it with different pillar files and configuration.
This is the commit where are the changes:
- Pillar-ExporterCore-ThibaultArloing.265
- Pillar-Model-ThibaultArloing.247

and the tests:
- Pillar-Tests-Model-ThibaultArloing.182
