### ISSUE TITLE
Use Header and Footer

### ISSUE THREAD

**Issue by Nymerea** [pillar-markup/pillar#105]
Hello,

I have a report to write for my school, and I would like to use pillar for it !

I wonder if there is a way to include header / footer in each page without include it manually ?

Also, there is a way to have "page x/ total" on each page ?

Kind regards

**Comment by jecisc** [comment]
Hi,
You can use a template to achieve that. I can send you an example went I will be home. 
There is an example on the Enterprise Pharo book.

**Comment by jecisc** [comment]
https://ci.inria.fr/pharo-contribution/job/EnterprisePharoBook/lastSuccessfulBuild/artifact/book-result/PillarChap/Pillar.html

**Comment by jecisc** [comment]
I did a university report with Pillar. Here is a link to my folder: https://drive.google.com/folderview?id=0B_KDRvt7h6lYMzZzVVA3ei1tMTQ&usp=sharing

There is the pillar version, the pdf version and the templates. 

The templates are not from me, so there is a lot of useless things in it, but it should help you. 

Since I used an old version of Pillar this might not be compatible with the latest version. But at least you can have an example.

**Comment by Nymerea** [comment]
Hi !

Thanks a million for your example but it doesn't fit to my need.

There is no header/footer and the number of page doesn't seem to be in your .pillar (and it's not in every pdf page)

**Comment by DamienCassou** [comment]
@Nymerea what do you want in your header/footer? Do you know LaTeX? Often, page numbers are not on title pages, this is a deliberate choice.

**Comment by Nymerea** [comment]
I would like my School logo and compagny logo appear in each header page and the autor (me) with the current page number in each footer page.

No I don't know laTex, that Why I would like to use pillar (seems to be easier syntax)

**Comment by DamienCassou** [comment]
Nymerea <notifications@github.com> writes:

> I would like my School logo and compagny logo appear in each header
> page and the autor (me) with the current page number in each footer
> page. No I don't know laTex, that Why I would like to use pillar
> (seems to be easier syntax)

creating the content of the document is indeed simpler in Pillar. But
Pillar only takes care of the content, the body, of your document. Not
what is around it. For that, you either have to use an existing template
(but none suit your needs), adapt an existing one (you could start from
Cyril's one) or create one from scratch. I suggest you quickly skim
through "The not so short introduction to LaTeX" which is freely
available on the web and ask your questions on tex.stackexchange.com
which is more appropriate. Pillar can't help you here.

-- 
Damien Cassou
http://damiencassou.seasidehosting.st

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill

**Comment by jecisc** [comment]
This issue is not the goal of pillar and the feature is covered by the templates ==> close
