### ISSUE TITLE
Input files on command lines are now ignored

### ISSUE THREAD

**Issue by DamienCassou** [pillar-markup/pillar#109]
In the mooc, when I use `./compile1Slide.sh Slides/Week1/C019-W1S06-ClassAndMethodDefinition.pillar`, the whole mooc is exported.

**Comment by ThibaultAr** [comment]
There is the same problem with `./compile1Exercise` but not with `./compile1Chapter.sh` in EnterprisePharo. 
I'll have a look at where it comes from

**Comment by YannDub** [comment]
It's fix in the stable version.

**Comment by DamienCassou** [comment]
Yann Dubois <notifications@github.com> writes:

> It's fix in the stable version.

thanks!

-- 
Damien Cassou
http://damiencassou.seasidehosting.st

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill
