### ISSUE TITLE
Provide helpful message when STON parser fails

### ISSUE THREAD

**Issue by cdlm** [pillar-markup/pillar#110]
Currently you get a stack trace and a character index but zero clue as to where the actual error is. Could be in `pillar.conf` or in the header metadata of any chapter…

**Comment by DamienCassou** [comment]
agree

**Comment by ThibaultAr** [comment]
I added a better message which specify from which file the error comes.

Cocoon-Core-ThibaultArloing.56
Cocoon-Tests-Core-ThibaultArloing.37

Pillar-Exporter-Core-ThibaultArloing.298
Pillar-Tests-Exporter-Core-ThibaultArloing.159

**Comment by DamienCassou** [comment]
what do the messages look like?

**Comment by ThibaultAr** [comment]
STONReaderError: At character 9: , expected Inside: BytecodeCompilation.pillar
or
CCConfigurationError: At character 9: , expected Inside: pillar.conf

**Comment by DamienCassou** [comment]
perfect, thanks
