### ISSUE TITLE
The configuration should have a group #parser.

### ISSUE THREAD

**Issue by jecisc** [pillar-markup/pillar#112]
The configuration should have a group parser because for now you cannot get only the parser and the html exporter for example.

This should be added in the dev AND stable baseline.

@YannDub @ThibaultAr : if one of you do it this next week, ping Esteban when you are done. He need it apparently.

**Comment by YannDub** [comment]
I added 2 groups, one for parser and another for parser tests. I wait an answer from Esteban

**Comment by YannDub** [comment]
fix with ConfigurationOfPillar-YannDubois.213
