### ISSUE TITLE
Make sure not to copy the outputDirectory to itself when it's part of support

### ISSUE THREAD

**Issue by DamienCassou** [pillar-markup/pillar#12]
When the `support` parameter includes (a part of) `outputDirectory`, Pillar will try to copy (the part of) `outputDirectory` to itself. We should make sure this does not happen by adding a special case to the code. For example, the following configuration is problematic:

```
{
  "support" : [ "**/figures" ]";
  "outputDirectory" : "result";
}
```

because the `result/` directory might include a `figures/` sub-directory: this will indeed happen when pillar is launched twice without removing the `result/` folder.

**Comment by guillep** [comment]
Fixed in latest stable. Special directories such as _result and support are ignored during the copy.
