### ISSUE TITLE
./pillar --help is plain bad

### ISSUE THREAD

**Issue by Ducasse** [pillar-markup/pillar#127]
28-06-16-PillarDev ./pillar --help
I am the top level command line handler for Pillar.

My keyword is "pillar".

I can not be used by myself, but I dispatch the rest of the command line to my sub command line handlers (see PRSubCommandLineHandler and its subclasses)

We should iterate over the subcommands and propose something decent.

**Comment by jecisc** [comment]
One think to know (that I learned recently) is that the --help option will print the content of the class comment by default.

So we need to improve the class comment to be more like the `PharoCommandLineHandler` one. As you said it could be cool to do it by iterating over the sub comments after we improve their comments.

**Comment by ThibaultAr** [comment]
I wrote an usage for pillar command
