### ISSUE TITLE
Double visiting of annotations

### ISSUE THREAD

**Issue by Ducasse** [pillar-markup/pillar#128]
With thibault we faced a really strange bug. 
We wanted to write an annotation that generates Pillar code. 
And the strange behavior was that the visitor was called two times (May be because of a phase). 

Here is how to reproduce it 

./pillar export --to=pillar Example.pillar

File: Example.pillar 
! Youpi

${cite:ref=Duca18rmod}$

!! Others

Then in the image

PRPillarWriter >> visitCitationAnnotation: aCitation
	"We invoke visitAnnotation: to make sure that the rest of the document is visited."

	self halt.
	super visitCitationAnnotation: aCitation

When we launch it, the halt is executed twice.

**Comment by YannDub** [comment]
I can't reproduce this bug. It's really strange because normally, a citation annotation is transformed before the export phase.

**Comment by YannDub** [comment]
Corrected in the last release (Pillar 4.0.4)
