### ISSUE TITLE
The configuration should be created in a phase and not in a command line handler

### ISSUE THREAD

**Issue by jecisc** [pillar-markup/pillar#129]
Currently the command line handler for the export create the configuration and launch the export. This should not be the responsibility of the CLI. We should have an object responsible for this. Since we have a nice phase logic, I think the configuration parse should be a phase.

What do you think? @YannDub @ThibaultAr

**Comment by YannDub** [comment]
I'm ok about this

**Comment by Ducasse** [comment]
I extracted the commandline logic into a builder. 
We will see if this is a phase or not later. 
First make it works, clean it. 
This is for Pharo 60 available as 4.0.10 or 4.0.11
