### ISSUE TITLE
Fix for gtInspectorPillarProjectIn

### ISSUE THREAD

**Issue by Ducasse** [pillar-markup/pillar#139]
FileReference >> gtInspectorPillarProjectIn: composite
	<gtInspectorPresentationOrder: 20>
	| pillarFile pillarConfiguration |
	self isDirectory not ifTrue: [ ^ self ].
	pillarFile := self files 
						detect: [:each | each basename = 'pillar.conf']
						ifNone: [ ^ self ].
	pillarConfiguration := PRPillarConfiguration new baseDirectory: self; importFromFile: pillarFile; yourself.
	(pillarConfiguration 
			gtInspectorInputFilesIn: composite)
			title: 'Pillar'

**Comment by Ducasse** [comment]
It seems that doru already fixed it. 
Name: Pillar-Pharo-Tools-TudorGirba.14
Author: TudorGirba
Time: 26 August 2016, 12:17:54.194858 pm
UUID: ead5bca7-6f2c-4bae-b2bb-218833570a4c
Ancestors: Pillar-Pharo-Tools-TudorGirba.13

fixed the file reference creation

**Comment by Alakathion** [comment]
Fixed in Pharo 6 release.
