### ISSUE TITLE
CLI: PRArchetype create... should be turned into a doIt method. 

### ISSUE THREAD

**Issue by Ducasse** [pillar-markup/pillar#143]
doIt is the method invoked once the configuration is created. 
But all the users are not correctly following this architecture. For example the PRArchetypeConfiguratioInstaller should probably not override the createConfiguration: but define a doIt method performing the download and action.

**Comment by guillep** [comment]
I refactored this a bit in the stable branch. There is still work to do but it is cleaner right now.
