### ISSUE TITLE
Error if we get two times an archetype

### ISSUE THREAD

**Issue by jecisc** [pillar-markup/pillar#146]
I just executed this two times and got an error. 
```
./pillar archetype welcome
```

**Comment by Ducasse** [comment]
which version? I do not see why pn pharo 50 it would not work.
if you want to help then we should sync because we are slowly making sure that 
we can move and refactor Pillar.

**Comment by Ducasse** [comment]
I never used twice the same installation because with me it never worked

**Comment by guillep** [comment]
This is working so far in the current stable branch.
