### ISSUE TITLE
Bug in HTML generation

### ISSUE THREAD

**Issue by Ducasse** [pillar-markup/pillar#154]
Apparently a filereference is added to the configuration and bark when jsonified

**Comment by Ducasse** [comment]
apparently
{
    "metadata": {
      "title":"My first document while reading the 5 minutes Pillar tutorial"
    }
}

!Hello World

is working but not

{
    "metadata": {
      "title":"My first document while reading the 5 minutes Pillar tutorial"
    },
    "outputDirectory" : "book-result"
}

!Hello World

there is a big mess with metadata look up and the rest.

**Comment by cdlm** [comment]
Pay attention that the makefile expects Pillar output in `build/` not `book-result/`. It can be changed but both need to agree. If Pillar can be asked the value of that `outputDirectory` setting from the command line, I can have the makefile rely on that instead of duplicating the info.

**Comment by Ducasse** [comment]
Thanks for pointing this out. 
The problem is that people can specify where they want the output to be located. 
We should do a pillar command line so that it can parse the configuration and returns this value. I will add a bug entry.

**Comment by Ducasse** [comment]
Ok so I changed the Makefile in welcome 
There is no build and not book-result. 
I changed the tutorial too. Like that the HTML generation is working in Pharo50. 
And we will see once we will have cleaned everything in Pharo 60.
