### ISSUE TITLE
Should integrate ConfigurationPartGenerator

### ISSUE THREAD

**Issue by Ducasse** [pillar-markup/pillar#173]
Bored to type all the inputFiles.... just asked for the generation.
Available in StephaneDucasse/PetitsBazars/ConfigurationPartGenerator.
Adding a command line would be nice too. 

I'm a little helper to generate inputFile list in pillar.conf
safari
(ConfigurationPartGenerator new configurationText) 
>>> 
'"inputFiles" : [
		"Slides/03-ObjectClassMethod/W3S01-WhatisAClass.pillar",
		"Slides/01-Welcome/W1S00-Intro-Objectives.pillar",
		"Slides/01-Welcome/W1S01-FirstLookAtClassObjectMethods.pillar",
		"Slides/01-Welcome/W1S04-PharoModelInaNushell.pillar",
		"Slides/01-Welcome/W1S05-PharoSyntaxInANutshell.pillar",
		"Slides/01-Welcome/W1S06-ClassAndMethodDefinition.pillar",
		"Slides/01-Welcome/W1S07-Blocks.pillar",
		"Slides/02-Syntax/W2S01-Messages.pillar",
		"Slides/02-Syntax/W2S02-Messages-ForTheJavaProgrammers.pillar",
		"Slides/02-Syntax/W2S03-Messages-Precedence.pillar",
		"Slides/02-Syntax/W2S04-Messages-Sequence.pillar",
		"Slides/1-ToReview/Basic-Blocks-Loops.pillar",
		"Slides/1-ToReview/Basic-Numbers.pillar",
		"Slides/1-ToReview/Intro-ObjectEssentialConcepts.pillar",
		"Slides/1-ToReview/Intro-Objectives.pillar",
		"Slides/1-ToReview/Intro-OOP.pillar",
],'

**Comment by guillep** [comment]
The stable version of pillar iterates the pillar base directory and finds by default all pillar files to build.
