### ISSUE TITLE
Rename script into codeBlock

### ISSUE THREAD

**Issue by Ducasse** [pillar-markup/pillar#182]
In the doc I renamed script into codeblock (called code in mardown) so we should rename the classes in Pharo and the visitors visit because this is super strange to have called this a script (was probably code snippet).

**Comment by samakhov** [comment]
It seems to be solved, but not closed. And I can't see those changes in my Pillar image (the new pipeline branch).

**Comment by guillep** [comment]
c6e68bf070b85cb7e42a8f5cb4a3431bff14fb8f renames also the visit* methods.
