### ISSUE TITLE
Cannot download pillar from ci.inria.fr

### ISSUE THREAD

**Issue by macie** [pillar-markup/pillar#184]
From about 3 days, when I try to download _pillar_ from **ci.inria.fr**, I get an error: **403 Unauthorized** (example link).

This issue also includes all public data resided in **ci.inria.fr**, for example books from @SquareBracketAssociates ([sample link](https://ci.inria.fr/pharo-contribution/job/EnterprisePharoBook/lastSuccessfulBuild/artifact/book-result/PillarChap/Pillar.html))

**Comment by Ducasse** [comment]
Can you explain how you are trying to donwload it?
Did it work before?
Do you follow the way explained in the Readme?

**Comment by Ducasse** [comment]
The link that you sent is not about downloading pillar, it is a chapter on pillar and this chapter can be found in the Entreprise Book on the http://books.pharo.org

**Comment by jecisc** [comment]
I think the problem is that now it requires to be logged to download content from pharo-contribution. This is bad.

**Comment by Ducasse** [comment]
Yes I agree and I will change it

**Comment by macie** [comment]
Yes, the problem was, that all resources (image with _pillar_, compiled book chapters) hosted on **ci.inria.fr**, weren't available to not logged users.

Now it works again. Thanks @Ducasse
