### ISSUE TITLE
Automatic section anchors

### ISSUE THREAD

**Issue by jecisc** [pillar-markup/pillar#19]
Each section title should automatically generate an [implicit hyperlink target](http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#implicit-hyperlink-targets) (aka, anchor) pointing to the section. The text of the hyperlink target (the "reference name") is the same as that of the section title.

**Comment by YannDub** [comment]
The users could enable or disable this enhancement ? Because I think for a static web site it could be better to choose.

**Comment by DamienCassou** [comment]
ok for me

**Comment by YannDub** [comment]
It's done with :
- Pillar-ExporterCore-YannDubois.264
- Pillar-Model-YannDubois.246

and tests :
- Pillar-Tests-Model-YannDubois.181

A todo is stay, because it's possible to have duplicated anchors

**Comment by YannDub** [comment]
I work on the duplicated anchors, and for now, the automatic generated anchors name are always encoded like :
anchorName@occurence

- anchorName : the name of the anchor.
- @ : a character to separate the the name and the occurence.
- occurence : the actual number (when I browse the tree) of the anchor.

But this way don't work when we have already an anchor with a name which will be generated, for example (in html) :

```
<h1>Test</h1>
....
<a id='Test@1'></a>
```

It will render after transformation :

```
<h1>Test</h1>
<a id='Test@1'></a>
....
<a id='Test@1'></a>
```

If you have a better idea...

**Comment by YannDub** [comment]
I managed the duplicated anchors with :
- Pillar-Model-YannDubois.252
- Pillar-Tests-Model-YannDubois.186

I use my previous post but I extend the idea to checking anchors before transformation.
