### ISSUE TITLE
installArchetypeNamed: 

### ISSUE THREAD

**Issue by Ducasse** [pillar-markup/pillar#193]
on travis-ci the integration builds are broken becausse of the missing installArchetypeNamed: 

MessageNotUnderstood: PRProject>>installArchetypeNamed:
PRProject(Object)>>doesNotUnderstand: #installArchetypeNamed:
PRIntegrationTest>>testArchetype:output: ...installArchetypeNamed: archetype

**Comment by Ducasse** [comment]
Now I check and in the head of new pipeline all the tests of PRIntegrationTest are green.

**Comment by Ducasse** [comment]
There is also 

archetypeNamed: aString 
	
	^ PRArchetype new
		name: aString;
		project: self;
		yourself

Now I do not get the travis builds are red for all the 
PRIntegrationTest tests :( No idea why so far.

**Comment by guillep** [comment]
In 942e34ec14f7918261b0cf5adbed8f65d08bf29f it looks like the method got renamed to `installArchetype:` but I remember that we did the opposite refactoring...

**Comment by Ducasse** [comment]
Fixed and travis
