### ISSUE TITLE
Semantic links

### ISSUE THREAD

**Issue by jecisc** [pillar-markup/pillar#21]
It would be nice to simplify the creation of links to standard websites such as Wikipedia and Youtube. For example, `+youtube:iJZYG5qwHHI+` would represent a particular video on Youtube and `*wikipedia:SOLID_(object-oriented_design)*` would be a link to a Wikipedia article on the SOLID principles. Beyond Youtube and Wikipedia, we could have links to Amazon, Google, Smalltalkhub, Github... Some links could be parametrized: for example, `+youtube:iJZYG5qwHHI|controls=0|showInfo=0+` would be the same as `+youtube:iJZYG5qwHHI+` without the player controls and video title.

**Comment by YannDub** [comment]
I thinks it's done /cc @lukaskom

**Comment by DamienCassou** [comment]
Please add a few lines in the Pillar chapter

**Comment by YannDub** [comment]
Done thanks @lukaskom
