### ISSUE TITLE
PRNodeTransformer class >> key should be removed

### ISSUE THREAD

**Issue by Ducasse** [pillar-markup/pillar#217]
It was used to express dependency between lightPhaser tasks. 
We do not use this anymore. 
We should check it.

**Comment by samakhov** [comment]
That method is expressed as an requirement for something. is it for lightPhaser ? As you say, if lightPhaser tasks have been removed, now this method is going to handle an error ??  If so, it can be removed.

**Comment by Ducasse** [comment]
Good question. 
This is why there is a bit of work to change the key usage. 

Stef

**Comment by guillep** [comment]
We need to remove that one plus the ones in the subclasses.

Of course all tests should be green afterwards :)

We have to check if they are not used for real.
