### ISSUE TITLE
PRMarkdownWriter inherits from PRHTMLWriter

### ISSUE THREAD

**Issue by guillep** [pillar-markup/pillar#227]
That looks odd

**Comment by samakhov** [comment]
PRMarkdownWriter have to inherit from PRDocumentWriter, not from PRHTMLWriter !! As for #canvasClass, all the methods redefine by Markdown come from DocumentWriter.

Asbath

**Comment by guillep** [comment]
Hi @samakhov, it would be nice if you try to fix one of the issues. Commenting is ok, but trying to fix one is even better ;)

**Comment by guillep** [comment]
This issue is fixed in 0d5f19ca2daa6fce028cd15d45350e3b6896a477
