### ISSUE TITLE
newpipeline does not work on Pharo70

### ISSUE THREAD

**Issue by Ducasse** [pillar-markup/pillar#261]
pillar build pdf
MessageNotUnderstood: ZnCharacterReadStream>>readStream
ZnCharacterReadStream(Object)>>doesNotUnderstand: #readStream
PRPillarParser class(PRPillarGrammar class)>>parse:

**Comment by guillep** [comment]
Now it does in latest dev-7. I've managed to put the parser code opening files in a single place, and then manage to use a pharo6 compatible API.
