### ISSUE TITLE
Remove SemanticLink and related

### ISSUE THREAD

**Issue by QDucasse** [pillar-markup/pillar#309]
(written by [Ducasse](https://github.com/Ducasse))

**Comment by jecisc** [comment]
I am really not sure since I don't have a Pillar image next to me but I think the goal was to add some links like a semantic link to a YouTube video and the HTML exporter would replace it by a video player in the HTML.

**Comment by Ducasse** [comment]
May be but it is not use.

**Comment by jecisc** [comment]
In any case it's easy to get it back if needed later.

**Comment by Ducasse** [comment]
Yes
