### ISSUE TITLE
Footnote

### ISSUE THREAD

**Issue by jecisc** [pillar-markup/pillar#35]
Add a footnote annotation on the pillar syntax. [http://orgmode.org/manual/External-links.html](http://orgmode.org/manual/External-links.html)

**Comment by YannDub** [comment]
I added this with a new transformer. Just LaTeX use this for the moment. It could be added to the others

**Comment by DamienCassou** [comment]
Please add this to at least HTML and Markdown before closing the issue.

**Comment by YannDub** [comment]
I had the footnote in :
- Markdown
- HTML
- Asciidoc

**Comment by DamienCassou** [comment]
do you have unit tests? If yes, you can probably close the issue. Thanks.

**Comment by YannDub** [comment]
Yes I have :)
