### ISSUE TITLE
Wrong bash lines for .bashrc

### ISSUE THREAD

**Issue by olekscode** [pillar-markup/pillar#365]
In README it is said that we need to add the following lines to `.bashrc`:
```bash
export PILLAR_HOME="$HOME/.pillar"
export PATH="$PATH:$PILLAR_HOME"
```
But in fact, since `pillar` is located in `build/` directory, it should be:
```bash
export PILLAR_HOME="$HOME/.pillar"
export PATH="$PATH:$PILLAR_HOME/build"
```

**Comment by Ducasse** [comment]
So apparently we fixed the readme.
