### ISSUE TITLE
Markdown exporter does not write a newline before a codeblock (``` ... ```)

### ISSUE THREAD

**Issue by tomooda** [pillar-markup/pillar#373]
a codeblock starts with a triple backticks **at the beginning of a line** like below

```
    Here is a code block
    ```smalltalk
    code stays here
    ``` 
```
However, PRMarkdownWriter emits a markdown like
```
    Here is a code block```smalltalk
    code stays here
    ```
```
This will not be parsed as a code block.

**Comment by Ducasse** [comment]
Yes I do not know who wrote it but the tests are not good

**Comment by tomooda** [comment]
OK, I committed a fix on the markdown writer tests. 
I see many other red tests. We should fix them soon.

**Comment by tomooda** [comment]
PR here. https://github.com/pillar-markup/pillar/pull/375
