### ISSUE TITLE
New parser for Pillar

### ISSUE THREAD

**Issue by jecisc** [pillar-markup/pillar#4]
The parser that takes text in Pillar syntax as input and produces a Pillar document tree as output is hard to understand and modify. It would be nice to refactor or rewrite it. Many unit-tests will guarantee that the new parser has the same behaviour as the old one.

**Comment by jecisc** [comment]
I created a PetitPillar parser that works but it still depend on the old parser.
We need to improve that.

**Comment by DamienCassou** [comment]
I think job is done at 90% (nearly all tests pass). The remaining 10% are details here and there where the new parser still depends on some pieces of the old one. Maybe the simplest thing to do is to move the parts that are useful from the old parser to the new one and remove the old. Then, in a second step, we can rewrite these parts in petit parser.

**Comment by jecisc** [comment]
I removed the dependency of the annotation parser.

Dependencies left:

- figures
- links
- raw

**Comment by jecisc** [comment]
Dependencies left:
- Raw

**Comment by jecisc** [comment]
An independent version of PetitPillar is ready :)
This version need test on real chapter to see if we do not lack of tests and if the time of parse is correct with the recent changes.

**Comment by jecisc** [comment]
The old parser was able to parse  ` ==\""bold""==` but PetitPillar no. should we charge PetitPillar or do we expect the user to write `\==bold\==` ? @DamienCassou

**Comment by jecisc** [comment]
For now PetitPillar have a problem if we have something as `==*== blabla ==*==` I think. It creates 1 format with 1 internal link with `== blabla ==` as reference.
The parse of the other contents of the format do not stop at the end of the format.

**Comment by jecisc** [comment]
Maybe the simpler would be to only have:

        boldFormat
            ^ boldMarkup, (escape / boldmarkup negate) star , boldMarkup

then re-parse the content to check formats, links, raw…

It's maybe not optimal but it will be hard to do better quickly.

**Comment by DamienCassou** [comment]
CyrilFerlicot <notifications@github.com> writes:
> The old parser was able to parse ` ==\""bold""==` but PetitPillar no.
> should we charge PetitPillar or do we expect the user to write
> `\==bold\==` ? @DamienCassou

when writing `==\""bold""==`, we expect Pillar to construct this
structure:

```
PRMonospace
  PRText: ""bold""
```

I think we want to keep have a way to write something that will generate
this structure: it could as well be `=="\"bold""==`. If you make this
second example work, no need to make the first work as well. We will fix
the books.

On the contrary, `\==bold\==` should have this structure

```
PRText: ==bold==
```

Each time we find something not parsing in the book, we should add a
unit test to detect the problem sooner.

-- 
Damien Cassou
http://damiencassou.seasidehosting.st

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill

**Comment by DamienCassou** [comment]
CyrilFerlicot <notifications@github.com> writes:

> For now PetitPillar have a problem if we have something as `==*== blabla ==*==` I think. It creates 1 format with 1 internal link with `== blabla ==` as reference.
> The parse of the other contents of the format do not stop at the end of the format.

If the writer wants a `*` in mono space, he should protect it: `==\*==
blabla ==\*==`. If the write wants to have an equal-equal inside a mono
space, he should protect it: `==\*=\= blabla =\=\*==`. If the user wants
an internal link in mono space, he should protect the equal-equal:
`==*=\= blabla =\=*==`.

-- 
Damien Cassou
http://damiencassou.seasidehosting.st

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill

**Comment by jecisc** [comment]
I updated the book and now the build pass :)

I think we can do a new configuration I think !

**Comment by jecisc** [comment]
Or maybe not… It seams we have some warnings we did not had before… I'll take a look later.

**Comment by jecisc** [comment]
Corrected !

**Comment by DamienCassou** [comment]
I validated the new parser on [ReadyForReviews chapters](https://github.com/SquareBracketAssociates/PharoReadyForReviews). Everything is fine there as well

**Comment by DamienCassou** [comment]
and on [InProgress chapters](https://github.com/SquareBracketAssociates/PharoInProgress/). Everything is fine there as well. I think we should release Pillar v2.0.0.

**Comment by jecisc** [comment]
:)

**Comment by jecisc** [comment]
Name: ConfigurationOfPillar-CyrilFerlicot.167
Author: CyrilFerlicot
Time: 11 September 2015, 12:05:10.764145 pm
UUID: 2af05692-ab27-3749-afc8-af3f061f6ccc
Ancestors: ConfigurationOfPillar-CyrilFerlicot.166
