### ISSUE TITLE
Structured data

### ISSUE THREAD

**Issue by jecisc** [pillar-markup/pillar#40]
Create a syntax to instantiate any object (aka. object literals). This is useful to create structured data and is similar to what [Wikipedia's Infobox](https://en.wikipedia.org/wiki/Help:Infobox) and [STON](https://github.com/svenvc/ston) provide.

**Comment by ThibaultAr** [comment]
I created a base for structured data
see: - Pillar-Model-ThibaultArloing.268
- Pillar-ExporterCore-ThibaultArloing.300

You can PRStructure and PRStructureTransformer to create a new Structure.
The syntax is the same as scripts with a parameter and JSON inside ,e.g.:
[[[structure=city
 {
   "name":"Lille",
   "postCode":"59000"
}
]]]

**Comment by DamienCassou** [comment]
I will have a look

**Comment by YannDub** [comment]
Done ? (/cc @ThibaultAr)

**Comment by DamienCassou** [comment]
Done! Thanks
