### ISSUE TITLE
Explain changes needed for non-english documents

### ISSUE THREAD

**Issue by cdlm** [pillar-markup/pillar#405]
The document's main language needs to be changed, e.g. at the beginning of `_support/latex/common.tex`:
```tex
% Non-english books should change the main language below; refer to `texdoc polyglossia`
% for supported languages and options.
\setmainlanguage{english}

% If needed, give a proper translation in your language for the title of the list of
% figures, tables, and listings which appears after the table of contents.
\addto\captionsfrench{\renewcommand*\listfigurename{Illustrations}}
%              ^^^^^^ (language identifier)         ^^^^^^^^^^^^^ (translated title)
```

Both definitions above are already done (for English) by the `sbabook` class, but should be adapted for other languages.

**Comment by cdlm** [comment]
Hyphenation patterns live in their own packages. So the `ensure-deps.sh` script should also require `hyphen-english` (or whatever language)

**Comment by Ducasse** [comment]
Is it for both 2018 and 2019?

**Comment by cdlm** [comment]
yes

**Comment by Ducasse** [comment]
I added hyphen-english to the ensure-deps and created a new issue on the publishing booklet.
