### ISSUE TITLE
Pillar exporter group not right

### ISSUE THREAD

**Issue by kasperosterbye** [pillar-markup/pillar#411]
This Metacello call:

```smalltalk
Metacello new
	baseline: 'PillarExporter';
	repository: 'github://pillar-markup/pillar:dev-7';
	load: 'pillar exporter'
```

seems to depend on something called Chrysal?

<img width="985" alt="image" src="https://user-images.githubusercontent.com/17723745/70920350-be2fc500-2022-11ea-9174-a6d7bc1628ee.png">

I just wanted to exported which can produce pillar source code from pillar model, so I can move back and forth between string representation and model.

**Comment by Ducasse** [comment]
I have to check. 
Chrysal is a lib to manage configuration and I use it to specify configurations. 
Now I do not know if the exporter can be used as standalone.

**Comment by kasperosterbye** [comment]
I found a workaround - seems I should not use the PillarExporter baseline.

This loads without problems:
```smalltalk
Metacello new
	baseline: 'Pillar';
	repository: 'github://pillar-markup/pillar:dev-7';
	load: 'pillar exporter'
```

**Comment by Ducasse** [comment]
Thanks I will have a look probably during holidays.
