### ISSUE TITLE
Add dependencies to CLAP of Pharo90

### ISSUE THREAD

**Issue by Ducasse** [pillar-markup/pillar#445]
- Need to find the magic invocation first
- then probably use a preLoadDoIt: 

baseline: spec
	<baseline>
	spec
		for: #common
		do: [
			spec preLoadDoIt: #'preload:package:'.

- and see

**Comment by Ducasse** [comment]
may be this

```
Metacello new baseline: #Clap;
 repository: 'gitlocal://.'; "parce que je build l'image dans mon clone git du repo…"
 onLock: [:ex :old :new | ex honor];
 ignoreImage; load.
```

**Comment by cdlm** [comment]
you could use the tag https://github.com/cdlm/clap-st/tree/pharo-pr5761 it's pointing at what @guillep merged in Pharo 9

**Comment by Ducasse** [comment]
Guille did it so I close this issue.
