### ISSUE TITLE
Richtext Conversion fails for monospace text starting with numbers.

### ISSUE THREAD

**Issue by udoschneider** [pillar-markup/pillar#544]
`PRRichTextComposer` fails converting content to Richtext when it encounters a monospace format starting with a number.

Minimalist test to reproduce:

```
PRDocument>>monospaceNumber
	^ self with: '123' format: PRMonospaceFormat

PRRichTextComposerTest>>testMonospaceWithNumberFormat 
	"self skip."
	self assertWriting: sample monospaceNumber include: self monospaceFormat
```

**Comment by jecisc** [comment]
PRRichTextComposer is not part of Pillar anymore since it is now managed by microdown. This issue can be closed.
