### ISSUE TITLE
Simple example not working

### ISSUE THREAD

**Issue by olekscode** [pillar-markup/pillar#576]
I have tried converting the most basic archetype from Pillar to Microdown and then compiling it to PDF:

1. `pillar archetype book`
2. `pillar build pdf` _(this works fine)_
3. `pillar convertBook index.pillar`  _(everything is converted to *.md - it seems correct)_
4. `pillar build pdf` _(now I get an error)_

```
ClapNamedMatch(ClapExpression)>>value:
[ :sub | sub value: arg ] in ClapCommand>>valueFor:with: in Block: [ :sub | sub value: arg ]
FullBlockClosure(BlockClosure)>>cull:
[ :cmdMatch | foundBlock cull: cmdMatch ] in ClapNamedMatch(ClapCompositeMatch)>>matchedSubcommand:ifNone: in Block: [ :cmdMatch | foundBlock cull: cmdMatch ]
FullBlockClosure(BlockClosure)>>cull:
[ :each | 
			(aBlock value: each)
				ifTrue: [ ^ foundBlock cull: each ] ] in OrderedCollection(Collection)>>detect:ifFound:ifNone: in Block: [ :each | ...
Syntax Error on line 4: 'Unmatched " in comment.'
=================================================
1: ."
2: 
3: 	^ (self globals ifNil: [ self globals: (IdentityDictionary new: 1) ])
4: 		at: aKey put: anObject
                          _^_
```

Perhaps, I am doing something wrong

**Comment by Ducasse** [comment]
did you try 
```
pillar build pdf index.md
```
because I did not remove the index.pillar to be able to check and it probably get used instead of the index.md

**Comment by olekscode** [comment]
Yes! This works perfectly.
And if I remove `index.pillar` then `pillar build pdf` also works!

Super cool!

I will close the issue

**Comment by Ducasse** [comment]
Good to know. 
may be now I should automatically rename the argument (or index.pillar) into a .old file
