### ISSUE TITLE
Bad dependency :(

### ISSUE THREAD

**Issue by guillep** [pillar-markup/pillar#583]
https://github.com/pillar-markup/pillar/blob/f28dad847ce6968d0700ecfe0d34fc70341ca43a/src/BaselineOfPillarApp/BaselineOfPillarApp.class.st#L32

I cannot build pillar v8.3.0 because it points to this version of microdown, which in turn depends on pillar dev-8. :(

https://github.com/pillar-markup/Microdown/blob/v2.3.1/src/BaselineOfMicrodown/BaselineOfMicrodown.class.st

Then, when microdown is loaded, pillar dev-8 is checked out and it breaks the build (because dev-8 moved a lot compared to v8.3.0)

**Comment by guillep** [comment]
I managed to build the latest version, but it would be nice to have reproducible versions...

**Comment by Ducasse** [comment]
Yes I really do not understand why this dependency escaped because I hate it.

**Comment by Ducasse** [comment]
updated the readme with correct information.
