### ISSUE TITLE
Remove embedded variable

### ISSUE THREAD

**Issue by jecisc** [pillar-markup/pillar#6]
Since we have a document item for the figures I think we do not need the «embedded» variable anymore. (in PRReference and subclasses)

**Comment by jecisc** [comment]
Before Figures was just a Link embedded  (on the model of Pillar) so we needed a special parameter to know if a link was a link or a figure.

Now the figures are not links. This "embedded" parameter is maybe not needed anymore.

**Comment by jecisc** [comment]
`embedded` is an instance variable, not a parameter. Sorry.

**Comment by jecisc** [comment]
For now `PRPillarWriter>>#visitReference` check if the reference is embedded or not to determine the markup.
I propose to remove that and add:

         PRPillarWriter>>#visitLink: aLink
            canvas raw: aLink class markup.
            super visitLink: aLink.
            canvas raw: aLink class markup

and 

        PRPillarWriter>>#visitFigure: aFigure
           canvas raw: aFigure class markupEmbedded.
           super visitFigure: aFigure.
           canvas raw: aFigure class markupEmbedded

but if I do that I need to remove some tests (or at least move them to specific subclasses) because now, for example, an external link have the possibility to be embedded (See PRExternalLinkTest(PRReferenceTest)>>#testParseEmbeddedAliased ). I think we do not want that.

**Comment by jecisc** [comment]
@DamienCassou what do you think of that ?

**Comment by jecisc** [comment]
I worked a little on it.
If @DamienCassou think it's good we can close the case with a new configuration of Pillar.

Name: Pillar-Model-CyrilFerlicot.228
Author: CyrilFerlicot
Time: 8 September 2015, 7:09:13.676662 pm
UUID: 9dccd0fa-b1d0-0042-9a1e-7a25e252ac60
Ancestors: Pillar-Model-DamienCassou.227

The embedded instance variable of reference is useless since we have Figures. I removed it and I improved the tests.

(See also Name: Pillar-Tests-ExporterMarkdown-CyrilFerlicot.28, Name: Pillar-Tests-ExporterCore-CyrilFerlicot.135, Name: Pillar-PetitPillar-CyrilFerlicot.100, Name: Pillar-ExporterPillar-CyrilFerlicot.32, Name: Pillar-Tests-ExporterLaTeX-CyrilFerlicot.97, Name: Pillar-Tests-Model-CyrilFerlicot.168)

**Comment by DamienCassou** [comment]
I love it. Now, is this change backward incompatible? If it is, we should release a `2.0.0` version. But I would like to have PetitPillar in by default if we do that. If it's not backward incompatible, we should release a `1.1.3`.

For me, this change is backward compatible because Pillar (as opposed to Pier) only had figures as embedded references, nothing else. So we don't loose any officially-supported feature with your patch.

What do you think?

**Comment by jecisc** [comment]
For me it is backward compatible because the users of Pillar itself will see no change. This is not a part of the public API. 
So I think we should do a `1.1.3`.

**Comment by DamienCassou** [comment]
this has been merged. Thanks Cyril
