### ISSUE TITLE
Pillar image does not exit when called from the command-line script

### ISSUE THREAD

**Issue by cdlm** [pillar-markup/pillar#60]

**Comment by jecisc** [comment]
This is maybe a problem of CommandLineHandler on Mac with the `--headless` inside the `pharo` script.

**Comment by DamienCassou** [comment]
the image should exit automatically when called headless and should stay open otherwise. This works well on linux

**Comment by cdlm** [comment]
Indeed, it works with the VM installed via download.sh, but fails with the one bundled in the Mac Pharo.app.

**Comment by cdlm** [comment]
closing, since it's an issue of the Mac VM
