### ISSUE TITLE
HTML entities appear in LaTeX listings environment

### ISSUE THREAD

**Issue by cdlm** [pillar-markup/pillar#74]
1. why HTML entities like `&gt;` in LaTeX output format?
2. code listings rely on `lstlistings` or `verbatim` which will display character escapes as-is

**Comment by DamienCassou** [comment]
how do I reproduce?

**Comment by cdlm** [comment]
```
git checkout sbabook
./compile.sh
grep -c '&[a-z]*;' book-result/**/*.tex
```

**Comment by DamienCassou** [comment]
```
"Font GentiumBookBasic not found."
```

**Comment by cdlm** [comment]
That's unrelated and happens after the pillar step.

On 23 September 2015 at 11:02, Damien Cassou <notifications@github.com>
wrote:

> ```
> "Font GentiumBookBasic not found."
> ```
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pillar-markup/pillar/issues/74#issuecomment-142535038>
> .
>



-- 
Damien Pollet
type less, do more [ | ] http://people.untyped.org/damien.pollet

**Comment by DamienCassou** [comment]
Ok, I found the problem and it's not related to Pillar. The problem is that Mustache escapes HTML characters by default. You have to explicitly ask to disable that in the Mustache template:

```diff
-«content»
+
+«! the '&' below prevents HTML escaping. »
+«& content»
```
