### ISSUE TITLE
PRCocoonConfiguration should be named PRPillarConfiguration

### ISSUE THREAD

**Issue by jecisc** [pillar-markup/pillar#86]
Feedback from Torsten: 
`I would have expected class "PRCocoonConfiguration" to be named "PRPillarConfiguration" because it typically represents "pillar.conf" and as the comment says "I manage pillar specific configuration." `

The reference to Cocoon should only be on the class comment.

@DamienCassou If you agree I will rename it.

**Comment by DamienCassou** [comment]
ok for me

**Comment by jecisc** [comment]
Done.
