### ISSUE TITLE
Jenkins doesn't compile Enterprise Pharo anymore.

### ISSUE THREAD

**Issue by jecisc** [pillar-markup/pillar#88]
From the latest build:

    […]
    + ./pharo Pharo.image eval --save 'Deprecation raiseWarning: false; showWarning: false.'
    Deprecation
    ./compile.sh
    + ./compile.sh
    fatal: Not a git repository (or any of the parent directories): .git
    rm -rf pharo-vm *.image *.change
    + rm -rf pharo-vm Pharo.image '*.change'
    […]

**Comment by cdlm** [comment]
I just checked, it's all green ?

On 6 November 2015 at 10:32, CyrilFerlicot <notifications@github.com> wrote:

> From the latest build:
>
> […]
> + ./pharo Pharo.image eval --save 'Deprecation raiseWarning: false; showWarning: false.'
> Deprecation
> ./compile.sh
> + ./compile.sh
> fatal: Not a git repository (or any of the parent directories): .git
> rm -rf pharo-vm *.image *.change
> + rm -rf pharo-vm Pharo.image '*.change'
> […]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pillar-markup/pillar/issues/88>.
>



-- 
Damien Pollet
type less, do more [ | ] http://people.untyped.org/damien.pollet

**Comment by jecisc** [comment]
It's green but it just run the tests. The build should run the tests then compile successfuly an entier Pillar book.

**Comment by cdlm** [comment]
Well then it shouldn't be green :)

**Comment by cdlm** [comment]
And I see a PDF in here… https://ci.inria.fr/pharo-contribution/view/Books/job/EnterprisePharoBook/216/artifact/book-result/
