### ISSUE TITLE
Improve build process

### ISSUE THREAD

**Issue by cdlm** [pillar-markup/pillar#89]
The steps of the build process (`compile.sh` and such scripts) are not really independent.

The `pillarPostExport.sh` script gets overwritten, so if you just built a single chapter and you now want to build the whole book, then you have to rerun `pillar export` even if nothing changed. I think this indicates that pillar is trying to do too much. It's trying to be a full build process when it should be just a pillar-to-other-formats exporter that is used a a step in a build process.

It should also be possible to separate parsing from generating. One possibility is to save a temporary version of the image after parsing. That image could then be run to export any chapter, or it could be rebuilt whenever a source file changes.

**Comment by DamienCassou** [comment]
Please report separate issues.

**Comment by cdlm** [comment]
Then don't close the issue until it was split…

**Comment by YannDub** [comment]
I think this issue is solved with the new compilation system (Makefile and latexmk), am I right ?

**Comment by DamienCassou** [comment]
OK for me. Thanks
