### ISSUE TITLE
Support SVG files as images

### ISSUE THREAD

**Issue by cdlm** [pillar-markup/pillar#91]
- `+file://images/foo.png+` → image included (`<img src=…` in HTML)
- `+file://images/foo.svg+` → link to SVG file (`<a href=…` ಠ_ಠ)

**Comment by DamienCassou** [comment]
What did you expect? I'm not sure webbrowser can contain inline svg with `<img ...`

**Comment by cdlm** [comment]
It's not inline. I tried by compiling the pillar file with a PNG version of the image, then replacing the file extension in the HTML code (so `<img src="images/foo.svg">`)

Including the SVG tags directly in the middle of HTML is also supposed to be OK but that probably depends more on the kind of HTML being generated (HTML5 or XHTML or…)

**Comment by cdlm** [comment]
I just upgraded Pillar in the image I was using and this seems to be working now. Thanks
