### ISSUE TITLE
Don't be too clever with listing arguments

### ISSUE THREAD

**Issue by cdlm** [pillar-markup/pillar#95]
When exporting to LaTeX, Pillar omits the `language` parameter when its value is not one of a predefined set (for instance `language=plain`; that's confusing. This is due to `PRRealScriptLanguage>>isSyntaxHighlightingPossible` and related code.

I think it would be best if Pillar exported the `language` parameter as specified. I guess the original use case was for HTML export and the JS colorizers which are not easily extensible; in this case, which values get exported should depend on the exporter, not on the script element.

**Comment by DamienCassou** [comment]
what I wanted to do was to abstract away from what LaTeX listings propose. Because maybe the language is named "smalltalk" in listings, but "Smalltalk80" in this particular JS library and "Pharo" in this other one. What is your problem exactly?

**Comment by cdlm** [comment]
My problem is you specify a language in the pillar file, and you get nothing in LaTeX.

What you explain is the same problem: `#isSyntaxHighlightingPossible` is **not** a responsibility of the document model, since it's exporter-specific. And in the case where the language is not known, Pillar should assume the author knows what they are doing instead of dropping that metadata.

Concretely, I have bugs in LaTeX when a listing begins with either of `{[#`. The listing environment tries to parse its contents and those characters conflict with the environment's optional argument. One solution would be to make the argument mandatory (and leave it empty if there is nothing to pass there). As a first step I was trying to add the language attribute to all problematic listings, but Pillar ignores it unless it's declared as a subclass of `PRRealScriptLanguage` (which is misnamed BTW: it's a listing language).

**Comment by DamienCassou** [comment]
I fixed this in Pillar-ExporterLaTeX-DamienCassou.92
